name: mydumper Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Coverage
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make coverage
        bash <(curl -s https://codecov.io/bash) -f "!mock.go" -t 139cd284-7f04-4e98-9e4b-4c697f007b59
